class AgentCtrl(object):
    """Mealy transducer.

    Internal states are integers, the current state
    is stored in the attribute "state".
    To take a transition, call method "move".

    The names of input variables are stored in the
    attribute "input_vars".

    Automatically generated by tulip.dumpsmach on 2024-01-27 21:12:19 UTC
    To learn more about TuLiP, visit http://tulip-control.org
    """
    def __init__(self):
        self.state = 110
        self.input_vars = ['Z_t', 'X_t']

    def move(self, Z_t, X_t):
        """Given inputs, take move and return outputs.

        @rtype: dict
        @return: dictionary with keys of the output variable names:
            ['x', 'z']
        """
        output = dict()
        if self.state == 0:
            if (Z_t == 6) and (X_t == 2):
                self.state = 0

                output["x"] = 0
                output["z"] = 6
            elif (Z_t == 5) and (X_t == 2):
                self.state = 1

                output["x"] = 1
                output["z"] = 6
            elif (Z_t == -1) and (X_t == 2):
                self.state = 2

                output["x"] = 0
                output["z"] = 6
            else:
                self._error(Z_t, X_t)
        elif self.state == 1:
            if (Z_t == 4) and (X_t == 2):
                self.state = 13

                output["x"] = 2
                output["z"] = 6
            elif (Z_t == 5) and (X_t == 2):
                self.state = 14

                output["x"] = 2
                output["z"] = 6
            elif (Z_t == 3) and (X_t == 2):
                self.state = 15

                output["x"] = 2
                output["z"] = 6
            else:
                self._error(Z_t, X_t)
        elif self.state == 2:
            if (Z_t == -1) and (X_t == 2):
                self.state = 3

                output["x"] = 1
                output["z"] = 6
            else:
                self._error(Z_t, X_t)
        elif self.state == 3:
            if (Z_t == -1) and (X_t == 2):
                self.state = 4

                output["x"] = 2
                output["z"] = 6
            else:
                self._error(Z_t, X_t)
        elif self.state == 4:
            if (Z_t == -1) and (X_t == 2):
                self.state = 5

                output["x"] = 2
                output["z"] = 5
            else:
                self._error(Z_t, X_t)
        elif self.state == 5:
            if (Z_t == -1) and (X_t == 2):
                self.state = 6

                output["x"] = 2
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 6:
            if (Z_t == -1) and (X_t == 2):
                self.state = 7

                output["x"] = 2
                output["z"] = 3
            else:
                self._error(Z_t, X_t)
        elif self.state == 7:
            if (Z_t == -1) and (X_t == 2):
                self.state = 8

                output["x"] = 2
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 8:
            if (Z_t == -1) and (X_t == 2):
                self.state = 9

                output["x"] = 2
                output["z"] = 1
            else:
                self._error(Z_t, X_t)
        elif self.state == 9:
            if (Z_t == -1) and (X_t == 2):
                self.state = 10

                output["x"] = 2
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 10:
            if (Z_t == -1) and (X_t == 2):
                self.state = 11

                output["x"] = 1
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 11:
            if (Z_t == -1) and (X_t == 2):
                self.state = 12

                output["x"] = 0
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 12:
            if (Z_t == -1) and (X_t == 2):
                self.state = 12

                output["x"] = 0
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 13:
            if (Z_t == 4) and (X_t == 2):
                self.state = 13

                output["x"] = 2
                output["z"] = 6
            elif (Z_t == 5) and (X_t == 2):
                self.state = 92

                output["x"] = 3
                output["z"] = 6
            elif (Z_t == 3) and (X_t == 2):
                self.state = 15

                output["x"] = 2
                output["z"] = 6
            else:
                self._error(Z_t, X_t)
        elif self.state == 14:
            if (Z_t == 4) and (X_t == 2):
                self.state = 13

                output["x"] = 2
                output["z"] = 6
            elif (Z_t == 5) and (X_t == 2):
                self.state = 92

                output["x"] = 3
                output["z"] = 6
            elif (Z_t == 3) and (X_t == 2):
                self.state = 15

                output["x"] = 2
                output["z"] = 6
            else:
                self._error(Z_t, X_t)
        elif self.state == 15:
            if (Z_t == 4) and (X_t == 2):
                self.state = 16

                output["x"] = 2
                output["z"] = 5
            elif (Z_t == 2) and (X_t == 2):
                self.state = 17

                output["x"] = 2
                output["z"] = 6
            elif (Z_t == 3) and (X_t == 2):
                self.state = 18

                output["x"] = 2
                output["z"] = 5
            else:
                self._error(Z_t, X_t)
        elif self.state == 16:
            if (Z_t == 4) and (X_t == 2):
                self.state = 16

                output["x"] = 2
                output["z"] = 5
            elif (Z_t == 5) and (X_t == 2):
                self.state = 90

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 20

                output["x"] = 2
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 17:
            if (Z_t == 2) and (X_t == 2):
                self.state = 17

                output["x"] = 2
                output["z"] = 6
            elif (Z_t == 1) and (X_t == 2):
                self.state = 86

                output["x"] = 2
                output["z"] = 6
            elif (Z_t == 3) and (X_t == 2):
                self.state = 18

                output["x"] = 2
                output["z"] = 5
            else:
                self._error(Z_t, X_t)
        elif self.state == 18:
            if (Z_t == 4) and (X_t == 2):
                self.state = 16

                output["x"] = 2
                output["z"] = 5
            elif (Z_t == 2) and (X_t == 2):
                self.state = 19

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 20

                output["x"] = 2
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 19:
            if (Z_t == 2) and (X_t == 2):
                self.state = 19

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 1) and (X_t == 2):
                self.state = 82

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 22

                output["x"] = 1
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 20:
            if (Z_t == 4) and (X_t == 2):
                self.state = 21

                output["x"] = 2
                output["z"] = 3
            elif (Z_t == 2) and (X_t == 2):
                self.state = 19

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 22

                output["x"] = 1
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 21:
            if (Z_t == 4) and (X_t == 2):
                self.state = 31

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 5) and (X_t == 2):
                self.state = 74

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 33

                output["x"] = 2
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 22:
            if (Z_t == 4) and (X_t == 2):
                self.state = 23

                output["x"] = 0
                output["z"] = 4
            elif (Z_t == 2) and (X_t == 2):
                self.state = 24

                output["x"] = 0
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 25

                output["x"] = 0
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 23:
            if (Z_t == 4) and (X_t == 2):
                self.state = 23

                output["x"] = 0
                output["z"] = 4
            elif (Z_t == 5) and (X_t == 2):
                self.state = 80

                output["x"] = 0
                output["z"] = 3
            elif (Z_t == 3) and (X_t == 2):
                self.state = 26

                output["x"] = 0
                output["z"] = 3
            else:
                self._error(Z_t, X_t)
        elif self.state == 24:
            if (Z_t == 2) and (X_t == 2):
                self.state = 24

                output["x"] = 0
                output["z"] = 4
            elif (Z_t == 1) and (X_t == 2):
                self.state = 75

                output["x"] = 0
                output["z"] = 3
            elif (Z_t == 3) and (X_t == 2):
                self.state = 26

                output["x"] = 0
                output["z"] = 3
            else:
                self._error(Z_t, X_t)
        elif self.state == 25:
            if (Z_t == 4) and (X_t == 2):
                self.state = 23

                output["x"] = 0
                output["z"] = 4
            elif (Z_t == 2) and (X_t == 2):
                self.state = 24

                output["x"] = 0
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 26

                output["x"] = 0
                output["z"] = 3
            else:
                self._error(Z_t, X_t)
        elif self.state == 26:
            if (Z_t == 4) and (X_t == 2):
                self.state = 27

                output["x"] = 0
                output["z"] = 2
            elif (Z_t == 2) and (X_t == 2):
                self.state = 28

                output["x"] = 0
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 29

                output["x"] = 0
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 27:
            if (Z_t == 4) and (X_t == 2):
                self.state = 27

                output["x"] = 0
                output["z"] = 2
            elif (Z_t == 5) and (X_t == 2):
                self.state = 73

                output["x"] = 1
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 30

                output["x"] = 1
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 28:
            if (Z_t == 2) and (X_t == 2):
                self.state = 28

                output["x"] = 0
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 72

                output["x"] = 1
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 30

                output["x"] = 1
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 29:
            if (Z_t == 4) and (X_t == 2):
                self.state = 27

                output["x"] = 0
                output["z"] = 2
            elif (Z_t == 2) and (X_t == 2):
                self.state = 28

                output["x"] = 0
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 30

                output["x"] = 1
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 30:
            if (Z_t == 4) and (X_t == 2):
                self.state = 31

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 2) and (X_t == 2):
                self.state = 32

                output["x"] = 1
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 33

                output["x"] = 2
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 31:
            if (Z_t == 4) and (X_t == 2):
                self.state = 31

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 5) and (X_t == 2):
                self.state = 71

                output["x"] = 2
                output["z"] = 1
            elif (Z_t == 3) and (X_t == 2):
                self.state = 35

                output["x"] = 2
                output["z"] = 1
            else:
                self._error(Z_t, X_t)
        elif self.state == 32:
            if (Z_t == 2) and (X_t == 2):
                self.state = 32

                output["x"] = 1
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 50

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 33

                output["x"] = 2
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 33:
            if (Z_t == 4) and (X_t == 2):
                self.state = 31

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 2) and (X_t == 2):
                self.state = 34

                output["x"] = 2
                output["z"] = 1
            elif (Z_t == 3) and (X_t == 2):
                self.state = 35

                output["x"] = 2
                output["z"] = 1
            else:
                self._error(Z_t, X_t)
        elif self.state == 34:
            if (Z_t == 2) and (X_t == 2):
                self.state = 38

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 48

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 37

                output["x"] = 2
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 35:
            if (Z_t == 4) and (X_t == 2):
                self.state = 36

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 34

                output["x"] = 2
                output["z"] = 1
            elif (Z_t == 3) and (X_t == 2):
                self.state = 37

                output["x"] = 2
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 36:
            if (Z_t == 4) and (X_t == 2):
                self.state = 36

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 5) and (X_t == 2):
                self.state = 47

                output["x"] = 1
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 39

                output["x"] = 1
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 37:
            if (Z_t == 4) and (X_t == 2):
                self.state = 36

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 38

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 39

                output["x"] = 1
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 38:
            if (Z_t == 2) and (X_t == 2):
                self.state = 38

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 46

                output["x"] = 1
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 39

                output["x"] = 1
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 39:
            if (Z_t == 4) and (X_t == 2):
                self.state = 40

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 41

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 42

                output["x"] = 0
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 40:
            if (Z_t == 4) and (X_t == 2):
                self.state = 40

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 5) and (X_t == 2):
                self.state = 45

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 42

                output["x"] = 0
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 41:
            if (Z_t == 2) and (X_t == 2):
                self.state = 41

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 43

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 42

                output["x"] = 0
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 42:
            if (Z_t == 4) and (X_t == 2):
                self.state = 40

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 41

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 42

                output["x"] = 0
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 43:
            if (Z_t == 0) and (X_t == 2):
                self.state = 44

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 41

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 43

                output["x"] = 0
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 44:
            if (Z_t == 0) and (X_t == 2):
                self.state = 44

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 43

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == -1) and (X_t == 2):
                self.state = 12

                output["x"] = 0
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 45:
            if (Z_t == 4) and (X_t == 2):
                self.state = 40

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 5) and (X_t == 2):
                self.state = 45

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 42

                output["x"] = 0
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 46:
            if (Z_t == 0) and (X_t == 2):
                self.state = 44

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 41

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 43

                output["x"] = 0
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 47:
            if (Z_t == 4) and (X_t == 2):
                self.state = 40

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 5) and (X_t == 2):
                self.state = 45

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 42

                output["x"] = 0
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 48:
            if (Z_t == 0) and (X_t == 2):
                self.state = 49

                output["x"] = 1
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 38

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 46

                output["x"] = 1
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 49:
            if (Z_t == 0) and (X_t == 2):
                self.state = 44

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 43

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == -1) and (X_t == 2):
                self.state = 12

                output["x"] = 0
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 50:
            if (Z_t == 0) and (X_t == 2):
                self.state = 51

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 2) and (X_t == 2):
                self.state = 34

                output["x"] = 2
                output["z"] = 1
            elif (Z_t == 1) and (X_t == 2):
                self.state = 52

                output["x"] = 3
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 51:
            if (Z_t == 0) and (X_t == 2):
                self.state = 51

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 52

                output["x"] = 3
                output["z"] = 2
            elif (Z_t == -1) and (X_t == 2):
                self.state = 8

                output["x"] = 2
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 52:
            if (Z_t == 0) and (X_t == 2):
                self.state = 53

                output["x"] = 4
                output["z"] = 2
            elif (Z_t == 2) and (X_t == 2):
                self.state = 54

                output["x"] = 4
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 55

                output["x"] = 4
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 53:
            if (Z_t == 0) and (X_t == 2):
                self.state = 53

                output["x"] = 4
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 56

                output["x"] = 4
                output["z"] = 1
            elif (Z_t == -1) and (X_t == 2):
                self.state = 69

                output["x"] = 4
                output["z"] = 1
            else:
                self._error(Z_t, X_t)
        elif self.state == 54:
            if (Z_t == 2) and (X_t == 2):
                self.state = 54

                output["x"] = 4
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 56

                output["x"] = 4
                output["z"] = 1
            elif (Z_t == 3) and (X_t == 2):
                self.state = 64

                output["x"] = 4
                output["z"] = 1
            else:
                self._error(Z_t, X_t)
        elif self.state == 55:
            if (Z_t == 0) and (X_t == 2):
                self.state = 53

                output["x"] = 4
                output["z"] = 2
            elif (Z_t == 2) and (X_t == 2):
                self.state = 54

                output["x"] = 4
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 56

                output["x"] = 4
                output["z"] = 1
            else:
                self._error(Z_t, X_t)
        elif self.state == 56:
            if (Z_t == 0) and (X_t == 2):
                self.state = 57

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 58

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 59

                output["x"] = 4
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 57:
            if (Z_t == 0) and (X_t == 2):
                self.state = 57

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 60

                output["x"] = 3
                output["z"] = 0
            elif (Z_t == -1) and (X_t == 2):
                self.state = 63

                output["x"] = 3
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 58:
            if (Z_t == 2) and (X_t == 2):
                self.state = 58

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 60

                output["x"] = 3
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 62

                output["x"] = 3
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 59:
            if (Z_t == 0) and (X_t == 2):
                self.state = 57

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 58

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 60

                output["x"] = 3
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 60:
            if (Z_t == 0) and (X_t == 2):
                self.state = 61

                output["x"] = 3
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 38

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 48

                output["x"] = 2
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 61:
            if (Z_t == 0) and (X_t == 2):
                self.state = 61

                output["x"] = 3
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 48

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == -1) and (X_t == 2):
                self.state = 10

                output["x"] = 2
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 62:
            if (Z_t == 4) and (X_t == 2):
                self.state = 36

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 38

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 37

                output["x"] = 2
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 63:
            if (Z_t == -1) and (X_t == 2):
                self.state = 10

                output["x"] = 2
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 64:
            if (Z_t == 4) and (X_t == 2):
                self.state = 65

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 58

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 66

                output["x"] = 4
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 65:
            if (Z_t == 4) and (X_t == 2):
                self.state = 65

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 5) and (X_t == 2):
                self.state = 67

                output["x"] = 3
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 62

                output["x"] = 3
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 66:
            if (Z_t == 4) and (X_t == 2):
                self.state = 65

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 58

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 62

                output["x"] = 3
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 67:
            if (Z_t == 4) and (X_t == 2):
                self.state = 36

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 5) and (X_t == 2):
                self.state = 68

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 37

                output["x"] = 2
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 68:
            if (Z_t == 4) and (X_t == 2):
                self.state = 36

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 5) and (X_t == 2):
                self.state = 47

                output["x"] = 1
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 39

                output["x"] = 1
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 69:
            if (Z_t == -1) and (X_t == 2):
                self.state = 70

                output["x"] = 4
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 70:
            if (Z_t == -1) and (X_t == 2):
                self.state = 63

                output["x"] = 3
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 71:
            if (Z_t == 4) and (X_t == 2):
                self.state = 36

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 5) and (X_t == 2):
                self.state = 68

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 37

                output["x"] = 2
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 72:
            if (Z_t == 0) and (X_t == 2):
                self.state = 51

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 2) and (X_t == 2):
                self.state = 32

                output["x"] = 1
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 50

                output["x"] = 2
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 73:
            if (Z_t == 4) and (X_t == 2):
                self.state = 31

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 5) and (X_t == 2):
                self.state = 74

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 33

                output["x"] = 2
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 74:
            if (Z_t == 4) and (X_t == 2):
                self.state = 31

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 5) and (X_t == 2):
                self.state = 71

                output["x"] = 2
                output["z"] = 1
            elif (Z_t == 3) and (X_t == 2):
                self.state = 35

                output["x"] = 2
                output["z"] = 1
            else:
                self._error(Z_t, X_t)
        elif self.state == 75:
            if (Z_t == 0) and (X_t == 2):
                self.state = 76

                output["x"] = 0
                output["z"] = 2
            elif (Z_t == 2) and (X_t == 2):
                self.state = 28

                output["x"] = 0
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 77

                output["x"] = 0
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 76:
            if (Z_t == 0) and (X_t == 2):
                self.state = 76

                output["x"] = 0
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 72

                output["x"] = 1
                output["z"] = 2
            elif (Z_t == -1) and (X_t == 2):
                self.state = 78

                output["x"] = 0
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 77:
            if (Z_t == 0) and (X_t == 2):
                self.state = 76

                output["x"] = 0
                output["z"] = 2
            elif (Z_t == 2) and (X_t == 2):
                self.state = 28

                output["x"] = 0
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 72

                output["x"] = 1
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 78:
            if (Z_t == -1) and (X_t == 2):
                self.state = 79

                output["x"] = 1
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 79:
            if (Z_t == -1) and (X_t == 2):
                self.state = 8

                output["x"] = 2
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 80:
            if (Z_t == 4) and (X_t == 2):
                self.state = 27

                output["x"] = 0
                output["z"] = 2
            elif (Z_t == 5) and (X_t == 2):
                self.state = 81

                output["x"] = 0
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 29

                output["x"] = 0
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 81:
            if (Z_t == 4) and (X_t == 2):
                self.state = 27

                output["x"] = 0
                output["z"] = 2
            elif (Z_t == 5) and (X_t == 2):
                self.state = 73

                output["x"] = 1
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 30

                output["x"] = 1
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 82:
            if (Z_t == 0) and (X_t == 2):
                self.state = 83

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 2) and (X_t == 2):
                self.state = 84

                output["x"] = 2
                output["z"] = 3
            elif (Z_t == 1) and (X_t == 2):
                self.state = 85

                output["x"] = 2
                output["z"] = 3
            else:
                self._error(Z_t, X_t)
        elif self.state == 83:
            if (Z_t == 0) and (X_t == 2):
                self.state = 83

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 1) and (X_t == 2):
                self.state = 85

                output["x"] = 2
                output["z"] = 3
            elif (Z_t == -1) and (X_t == 2):
                self.state = 6

                output["x"] = 2
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 84:
            if (Z_t == 2) and (X_t == 2):
                self.state = 84

                output["x"] = 2
                output["z"] = 3
            elif (Z_t == 1) and (X_t == 2):
                self.state = 50

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 33

                output["x"] = 2
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 85:
            if (Z_t == 0) and (X_t == 2):
                self.state = 51

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 2) and (X_t == 2):
                self.state = 84

                output["x"] = 2
                output["z"] = 3
            elif (Z_t == 1) and (X_t == 2):
                self.state = 50

                output["x"] = 2
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 86:
            if (Z_t == 0) and (X_t == 2):
                self.state = 87

                output["x"] = 2
                output["z"] = 6
            elif (Z_t == 2) and (X_t == 2):
                self.state = 88

                output["x"] = 2
                output["z"] = 5
            elif (Z_t == 1) and (X_t == 2):
                self.state = 89

                output["x"] = 2
                output["z"] = 5
            else:
                self._error(Z_t, X_t)
        elif self.state == 87:
            if (Z_t == 0) and (X_t == 2):
                self.state = 87

                output["x"] = 2
                output["z"] = 6
            elif (Z_t == 1) and (X_t == 2):
                self.state = 89

                output["x"] = 2
                output["z"] = 5
            elif (Z_t == -1) and (X_t == 2):
                self.state = 4

                output["x"] = 2
                output["z"] = 6
            else:
                self._error(Z_t, X_t)
        elif self.state == 88:
            if (Z_t == 2) and (X_t == 2):
                self.state = 19

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 1) and (X_t == 2):
                self.state = 82

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 20

                output["x"] = 2
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 89:
            if (Z_t == 0) and (X_t == 2):
                self.state = 83

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 2) and (X_t == 2):
                self.state = 19

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 1) and (X_t == 2):
                self.state = 82

                output["x"] = 2
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 90:
            if (Z_t == 4) and (X_t == 2):
                self.state = 21

                output["x"] = 2
                output["z"] = 3
            elif (Z_t == 5) and (X_t == 2):
                self.state = 91

                output["x"] = 2
                output["z"] = 3
            elif (Z_t == 3) and (X_t == 2):
                self.state = 22

                output["x"] = 1
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 91:
            if (Z_t == 4) and (X_t == 2):
                self.state = 31

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 5) and (X_t == 2):
                self.state = 74

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 33

                output["x"] = 2
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 92:
            if (Z_t == 4) and (X_t == 2):
                self.state = 93

                output["x"] = 4
                output["z"] = 6
            elif (Z_t == 5) and (X_t == 2):
                self.state = 94

                output["x"] = 4
                output["z"] = 6
            elif (Z_t == 3) and (X_t == 2):
                self.state = 15

                output["x"] = 2
                output["z"] = 6
            else:
                self._error(Z_t, X_t)
        elif self.state == 93:
            if (Z_t == 4) and (X_t == 2):
                self.state = 93

                output["x"] = 4
                output["z"] = 6
            elif (Z_t == 5) and (X_t == 2):
                self.state = 95

                output["x"] = 4
                output["z"] = 5
            elif (Z_t == 3) and (X_t == 2):
                self.state = 96

                output["x"] = 4
                output["z"] = 5
            else:
                self._error(Z_t, X_t)
        elif self.state == 94:
            if (Z_t == 4) and (X_t == 2):
                self.state = 93

                output["x"] = 4
                output["z"] = 6
            elif (Z_t == 5) and (X_t == 2):
                self.state = 95

                output["x"] = 4
                output["z"] = 5
            elif (Z_t == 3) and (X_t == 2):
                self.state = 96

                output["x"] = 4
                output["z"] = 5
            else:
                self._error(Z_t, X_t)
        elif self.state == 95:
            if (Z_t == 4) and (X_t == 2):
                self.state = 97

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 5) and (X_t == 2):
                self.state = 109

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 99

                output["x"] = 4
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 96:
            if (Z_t == 4) and (X_t == 2):
                self.state = 97

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 2) and (X_t == 2):
                self.state = 98

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 99

                output["x"] = 4
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 97:
            if (Z_t == 4) and (X_t == 2):
                self.state = 97

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 5) and (X_t == 2):
                self.state = 108

                output["x"] = 3
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 100

                output["x"] = 3
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 98:
            if (Z_t == 2) and (X_t == 2):
                self.state = 98

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 1) and (X_t == 2):
                self.state = 102

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 100

                output["x"] = 3
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 99:
            if (Z_t == 4) and (X_t == 2):
                self.state = 97

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 2) and (X_t == 2):
                self.state = 98

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 100

                output["x"] = 3
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 100:
            if (Z_t == 4) and (X_t == 2):
                self.state = 101

                output["x"] = 3
                output["z"] = 4
            elif (Z_t == 2) and (X_t == 2):
                self.state = 19

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 20

                output["x"] = 2
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 101:
            if (Z_t == 4) and (X_t == 2):
                self.state = 101

                output["x"] = 3
                output["z"] = 4
            elif (Z_t == 5) and (X_t == 2):
                self.state = 90

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 20

                output["x"] = 2
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 102:
            if (Z_t == 0) and (X_t == 2):
                self.state = 103

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 2) and (X_t == 2):
                self.state = 104

                output["x"] = 3
                output["z"] = 4
            elif (Z_t == 1) and (X_t == 2):
                self.state = 105

                output["x"] = 3
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 103:
            if (Z_t == 0) and (X_t == 2):
                self.state = 103

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 1) and (X_t == 2):
                self.state = 105

                output["x"] = 3
                output["z"] = 4
            elif (Z_t == -1) and (X_t == 2):
                self.state = 106

                output["x"] = 4
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 104:
            if (Z_t == 2) and (X_t == 2):
                self.state = 19

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 1) and (X_t == 2):
                self.state = 82

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 20

                output["x"] = 2
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 105:
            if (Z_t == 0) and (X_t == 2):
                self.state = 83

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 2) and (X_t == 2):
                self.state = 19

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 1) and (X_t == 2):
                self.state = 82

                output["x"] = 2
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 106:
            if (Z_t == -1) and (X_t == 2):
                self.state = 107

                output["x"] = 3
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 107:
            if (Z_t == -1) and (X_t == 2):
                self.state = 6

                output["x"] = 2
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 108:
            if (Z_t == 4) and (X_t == 2):
                self.state = 101

                output["x"] = 3
                output["z"] = 4
            elif (Z_t == 5) and (X_t == 2):
                self.state = 90

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 20

                output["x"] = 2
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 109:
            if (Z_t == 4) and (X_t == 2):
                self.state = 97

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 5) and (X_t == 2):
                self.state = 108

                output["x"] = 3
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 100

                output["x"] = 3
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 110:
            if (Z_t == 6) and (X_t == 2):
                self.state = 0

                output["x"] = 0
                output["z"] = 6
            else:
                self._error(Z_t, X_t)
        else:
            raise Exception("Unrecognized internal state: " + str(self.state))
        return output

    def _error(self, Z_t, X_t):
        raise ValueError("Unrecognized input: " + (
            "Z_t = {Z_t}; "
            "X_t = {X_t}; ").format(
                Z_t=Z_t,
                X_t=X_t))
