class AgentCtrl(object):
    """Mealy transducer.

    Internal states are integers, the current state
    is stored in the attribute "state".
    To take a transition, call method "move".

    The names of input variables are stored in the
    attribute "input_vars".

    Automatically generated by tulip.dumpsmach on 2023-08-08 21:31:36 UTC
    To learn more about TuLiP, visit http://tulip-control.org
    """
    def __init__(self):
        self.state = 48
        self.input_vars = ['Z_t', 'X_t']

    def move(self, Z_t, X_t):
        """Given inputs, take move and return outputs.

        @rtype: dict
        @return: dictionary with keys of the output variable names:
            ['x', 'z']
        """
        output = dict()
        if self.state == 0:
            if (Z_t == 4) and (X_t == 2):
                self.state = 0

                output["x"] = 0
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 1

                output["x"] = 1
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 1:
            if (Z_t == 4) and (X_t == 2):
                self.state = 2

                output["x"] = 1
                output["z"] = 4
            elif (Z_t == 2) and (X_t == 2):
                self.state = 3

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 4

                output["x"] = 2
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 2:
            if (Z_t == 4) and (X_t == 2):
                self.state = 2

                output["x"] = 1
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 4

                output["x"] = 2
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 3:
            if (Z_t == 2) and (X_t == 2):
                self.state = 3

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 1) and (X_t == 2):
                self.state = 45

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 6

                output["x"] = 3
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 4:
            if (Z_t == 4) and (X_t == 2):
                self.state = 5

                output["x"] = 2
                output["z"] = 3
            elif (Z_t == 2) and (X_t == 2):
                self.state = 3

                output["x"] = 2
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 6

                output["x"] = 3
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 5:
            if (Z_t == 4) and (X_t == 2):
                self.state = 15

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 17

                output["x"] = 2
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 6:
            if (Z_t == 4) and (X_t == 2):
                self.state = 7

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 2) and (X_t == 2):
                self.state = 8

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 9

                output["x"] = 4
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        elif self.state == 7:
            if (Z_t == 4) and (X_t == 2):
                self.state = 7

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 10

                output["x"] = 4
                output["z"] = 3
            else:
                self._error(Z_t, X_t)
        elif self.state == 8:
            if (Z_t == 2) and (X_t == 2):
                self.state = 8

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 1) and (X_t == 2):
                self.state = 43

                output["x"] = 4
                output["z"] = 3
            elif (Z_t == 3) and (X_t == 2):
                self.state = 10

                output["x"] = 4
                output["z"] = 3
            else:
                self._error(Z_t, X_t)
        elif self.state == 9:
            if (Z_t == 4) and (X_t == 2):
                self.state = 7

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 2) and (X_t == 2):
                self.state = 8

                output["x"] = 4
                output["z"] = 4
            elif (Z_t == 3) and (X_t == 2):
                self.state = 10

                output["x"] = 4
                output["z"] = 3
            else:
                self._error(Z_t, X_t)
        elif self.state == 10:
            if (Z_t == 4) and (X_t == 2):
                self.state = 11

                output["x"] = 4
                output["z"] = 2
            elif (Z_t == 2) and (X_t == 2):
                self.state = 12

                output["x"] = 4
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 13

                output["x"] = 4
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 11:
            if (Z_t == 4) and (X_t == 2):
                self.state = 11

                output["x"] = 4
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 14

                output["x"] = 3
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 12:
            if (Z_t == 2) and (X_t == 2):
                self.state = 12

                output["x"] = 4
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 42

                output["x"] = 3
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 14

                output["x"] = 3
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 13:
            if (Z_t == 4) and (X_t == 2):
                self.state = 11

                output["x"] = 4
                output["z"] = 2
            elif (Z_t == 2) and (X_t == 2):
                self.state = 12

                output["x"] = 4
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 14

                output["x"] = 3
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 14:
            if (Z_t == 4) and (X_t == 2):
                self.state = 15

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 2) and (X_t == 2):
                self.state = 16

                output["x"] = 3
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 17

                output["x"] = 2
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 15:
            if (Z_t == 4) and (X_t == 2):
                self.state = 15

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 19

                output["x"] = 2
                output["z"] = 1
            else:
                self._error(Z_t, X_t)
        elif self.state == 16:
            if (Z_t == 2) and (X_t == 2):
                self.state = 16

                output["x"] = 3
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 30

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 17

                output["x"] = 2
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 17:
            if (Z_t == 4) and (X_t == 2):
                self.state = 15

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 2) and (X_t == 2):
                self.state = 18

                output["x"] = 2
                output["z"] = 1
            elif (Z_t == 3) and (X_t == 2):
                self.state = 19

                output["x"] = 2
                output["z"] = 1
            else:
                self._error(Z_t, X_t)
        elif self.state == 18:
            if (Z_t == 2) and (X_t == 2):
                self.state = 22

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 29

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 21

                output["x"] = 2
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 19:
            if (Z_t == 4) and (X_t == 2):
                self.state = 20

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 18

                output["x"] = 2
                output["z"] = 1
            elif (Z_t == 3) and (X_t == 2):
                self.state = 21

                output["x"] = 2
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 20:
            if (Z_t == 4) and (X_t == 2):
                self.state = 20

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 23

                output["x"] = 3
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 21:
            if (Z_t == 4) and (X_t == 2):
                self.state = 20

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 22

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 23

                output["x"] = 3
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 22:
            if (Z_t == 2) and (X_t == 2):
                self.state = 22

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 28

                output["x"] = 3
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 23

                output["x"] = 3
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 23:
            if (Z_t == 4) and (X_t == 2):
                self.state = 24

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 25

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 26

                output["x"] = 4
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 24:
            if (Z_t == 4) and (X_t == 2):
                self.state = 24

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 26

                output["x"] = 4
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 25:
            if (Z_t == 2) and (X_t == 2):
                self.state = 25

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 27

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 26

                output["x"] = 4
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 26:
            if (Z_t == 4) and (X_t == 2):
                self.state = 24

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 25

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 26

                output["x"] = 4
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 27:
            if (Z_t == 2) and (X_t == 2):
                self.state = 25

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 27

                output["x"] = 4
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 28:
            if (Z_t == 2) and (X_t == 2):
                self.state = 25

                output["x"] = 4
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 27

                output["x"] = 4
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 29:
            if (Z_t == 2) and (X_t == 2):
                self.state = 22

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 28

                output["x"] = 3
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 30:
            if (Z_t == 2) and (X_t == 2):
                self.state = 18

                output["x"] = 2
                output["z"] = 1
            elif (Z_t == 1) and (X_t == 2):
                self.state = 31

                output["x"] = 1
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 31:
            if (Z_t == 2) and (X_t == 2):
                self.state = 32

                output["x"] = 0
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 33

                output["x"] = 0
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 32:
            if (Z_t == 2) and (X_t == 2):
                self.state = 32

                output["x"] = 0
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 34

                output["x"] = 0
                output["z"] = 1
            elif (Z_t == 3) and (X_t == 2):
                self.state = 39

                output["x"] = 0
                output["z"] = 1
            else:
                self._error(Z_t, X_t)
        elif self.state == 33:
            if (Z_t == 2) and (X_t == 2):
                self.state = 32

                output["x"] = 0
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 34

                output["x"] = 0
                output["z"] = 1
            else:
                self._error(Z_t, X_t)
        elif self.state == 34:
            if (Z_t == 2) and (X_t == 2):
                self.state = 35

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 36

                output["x"] = 0
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 35:
            if (Z_t == 2) and (X_t == 2):
                self.state = 35

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 37

                output["x"] = 1
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 38

                output["x"] = 1
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 36:
            if (Z_t == 2) and (X_t == 2):
                self.state = 35

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 37

                output["x"] = 1
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 37:
            if (Z_t == 2) and (X_t == 2):
                self.state = 22

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 1) and (X_t == 2):
                self.state = 29

                output["x"] = 2
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 38:
            if (Z_t == 4) and (X_t == 2):
                self.state = 20

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 22

                output["x"] = 2
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 21

                output["x"] = 2
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 39:
            if (Z_t == 4) and (X_t == 2):
                self.state = 40

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 35

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 41

                output["x"] = 0
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 40:
            if (Z_t == 4) and (X_t == 2):
                self.state = 40

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 38

                output["x"] = 1
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 41:
            if (Z_t == 4) and (X_t == 2):
                self.state = 40

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 2) and (X_t == 2):
                self.state = 35

                output["x"] = 0
                output["z"] = 0
            elif (Z_t == 3) and (X_t == 2):
                self.state = 38

                output["x"] = 1
                output["z"] = 0
            else:
                self._error(Z_t, X_t)
        elif self.state == 42:
            if (Z_t == 2) and (X_t == 2):
                self.state = 16

                output["x"] = 3
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 30

                output["x"] = 2
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 43:
            if (Z_t == 2) and (X_t == 2):
                self.state = 12

                output["x"] = 4
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 44

                output["x"] = 4
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 44:
            if (Z_t == 2) and (X_t == 2):
                self.state = 12

                output["x"] = 4
                output["z"] = 2
            elif (Z_t == 1) and (X_t == 2):
                self.state = 42

                output["x"] = 3
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 45:
            if (Z_t == 2) and (X_t == 2):
                self.state = 46

                output["x"] = 2
                output["z"] = 3
            elif (Z_t == 1) and (X_t == 2):
                self.state = 47

                output["x"] = 2
                output["z"] = 3
            else:
                self._error(Z_t, X_t)
        elif self.state == 46:
            if (Z_t == 2) and (X_t == 2):
                self.state = 46

                output["x"] = 2
                output["z"] = 3
            elif (Z_t == 1) and (X_t == 2):
                self.state = 30

                output["x"] = 2
                output["z"] = 2
            elif (Z_t == 3) and (X_t == 2):
                self.state = 17

                output["x"] = 2
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 47:
            if (Z_t == 2) and (X_t == 2):
                self.state = 46

                output["x"] = 2
                output["z"] = 3
            elif (Z_t == 1) and (X_t == 2):
                self.state = 30

                output["x"] = 2
                output["z"] = 2
            else:
                self._error(Z_t, X_t)
        elif self.state == 48:
            if (Z_t == 4) and (X_t == 2):
                self.state = 0

                output["x"] = 0
                output["z"] = 4
            else:
                self._error(Z_t, X_t)
        else:
            raise Exception("Unrecognized internal state: " + str(self.state))
        return output

    def _error(self, Z_t, X_t):
        raise ValueError("Unrecognized input: " + (
            "Z_t = {Z_t}; "
            "X_t = {X_t}; ").format(
                Z_t=Z_t,
                X_t=X_t))
