class TesterCtrl(object):
    """Mealy transducer.

    Internal states are integers, the current state
    is stored in the attribute "state".
    To take a transition, call method "move".

    The names of input variables are stored in the
    attribute "input_vars".

    Automatically generated by tulip.dumpsmach on 2024-03-21 20:08:28 UTC
    To learn more about TuLiP, visit http://tulip-control.org
    """
    def __init__(self):
        self.state = 140
        self.input_vars = ['x', 'z', 'q']

    def move(self, x, z, q):
        """Given inputs, take move and return outputs.

        @rtype: dict
        @return: dictionary with keys of the output variable names:
            ['X_t', 'Z_t', 'turn']
        """
        output = dict()
        if self.state == 0:
            if (x == 0) and (z == 6) and (q == 0):
                self.state = 1

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 1:
            if (x == 0) and (z == 6) and (q == 0):
                self.state = 2

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 1
            elif (x == 1) and (z == 6) and (q == 0):
                self.state = 3

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 2:
            if (x == 0) and (z == 6) and (q == 0):
                self.state = 1

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 3:
            if (x == 1) and (z == 6) and (q == 0):
                self.state = 4

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 4:
            if (x == 0) and (z == 6) and (q == 0):
                self.state = 2

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 1
            elif (x == 2) and (z == 6) and (q == 0):
                self.state = 5

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 1
            elif (x == 1) and (z == 6) and (q == 0):
                self.state = 3

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 5:
            if (x == 2) and (z == 6) and (q == 0):
                self.state = 6

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 6:
            if (x == 2) and (z == 6) and (q == 0):
                self.state = 5

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 1
            elif (x == 1) and (z == 6) and (q == 0):
                self.state = 3

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 1
            elif (x == 3) and (z == 6) and (q == 0):
                self.state = 7

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 7:
            if (x == 3) and (z == 6) and (q == 0):
                self.state = 8

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 8:
            if (x == 4) and (z == 6) and (q == 0):
                self.state = 9

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 1
            elif (x == 2) and (z == 6) and (q == 0):
                self.state = 5

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 1
            elif (x == 3) and (z == 6) and (q == 0):
                self.state = 7

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 9:
            if (x == 4) and (z == 6) and (q == 0):
                self.state = 10

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 10:
            if (x == 4) and (z == 6) and (q == 0):
                self.state = 9

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 1
            elif (x == 4) and (z == 5) and (q == 15):
                self.state = 11

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 1
            elif (x == 3) and (z == 6) and (q == 0):
                self.state = 7

                output["X_t"] = 2
                output["Z_t"] = 5
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 11:
            if (x == 4) and (z == 5) and (q == 15):
                self.state = 12

                output["X_t"] = 2
                output["Z_t"] = 4
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 12:
            if (x == 4) and (z == 4) and (q == 15):
                self.state = 13

                output["X_t"] = 2
                output["Z_t"] = 4
                output["turn"] = 1
            elif (x == 4) and (z == 6) and (q == 15):
                self.state = 14

                output["X_t"] = 2
                output["Z_t"] = 4
                output["turn"] = 1
            elif (x == 4) and (z == 5) and (q == 15):
                self.state = 15

                output["X_t"] = 2
                output["Z_t"] = 4
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 13:
            if (x == 4) and (z == 4) and (q == 15):
                self.state = 139

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 14:
            if (x == 4) and (z == 6) and (q == 15):
                self.state = 20

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 15:
            if (x == 4) and (z == 5) and (q == 15):
                self.state = 16

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 16:
            if (x == 4) and (z == 4) and (q == 15):
                self.state = 17

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 4) and (z == 6) and (q == 15):
                self.state = 18

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 4) and (z == 5) and (q == 15):
                self.state = 19

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 17:
            if (x == 4) and (z == 4) and (q == 15):
                self.state = 139

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 18:
            if (x == 4) and (z == 6) and (q == 15):
                self.state = 20

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 19:
            if (x == 4) and (z == 5) and (q == 15):
                self.state = 16

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 20:
            if (x == 4) and (z == 6) and (q == 15):
                self.state = 18

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 4) and (z == 5) and (q == 15):
                self.state = 19

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 3) and (z == 6) and (q == 15):
                self.state = 21

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 21:
            if (x == 3) and (z == 6) and (q == 15):
                self.state = 22

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 22:
            if (x == 4) and (z == 6) and (q == 15):
                self.state = 18

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 2) and (z == 6) and (q == 15):
                self.state = 23

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 3) and (z == 6) and (q == 15):
                self.state = 21

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 23:
            if (x == 2) and (z == 6) and (q == 15):
                self.state = 24

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 24:
            if (x == 2) and (z == 6) and (q == 15):
                self.state = 23

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 2) and (z == 5) and (q == 15):
                self.state = 25

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 1) and (z == 6) and (q == 15):
                self.state = 26

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 3) and (z == 6) and (q == 15):
                self.state = 21

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 25:
            if (x == 2) and (z == 5) and (q == 15):
                self.state = 30

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 26:
            if (x == 1) and (z == 6) and (q == 15):
                self.state = 27

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 27:
            if (x == 0) and (z == 6) and (q == 15):
                self.state = 28

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 2) and (z == 6) and (q == 15):
                self.state = 23

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 1) and (z == 6) and (q == 15):
                self.state = 26

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 28:
            if (x == 0) and (z == 6) and (q == 15):
                self.state = 29

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 29:
            if (x == 0) and (z == 6) and (q == 15):
                self.state = 28

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 1) and (z == 6) and (q == 15):
                self.state = 26

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 30:
            if (x == 2) and (z == 4) and (q == 15):
                self.state = 31

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 2) and (z == 6) and (q == 15):
                self.state = 23

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 2) and (z == 5) and (q == 15):
                self.state = 25

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 31:
            if (x == 2) and (z == 4) and (q == 15):
                self.state = 32

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 32:
            if (x == 2) and (z == 4) and (q == 15):
                self.state = 31

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 2) and (z == 5) and (q == 15):
                self.state = 25

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 1) and (z == 4) and (q == 15):
                self.state = 33

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 3) and (z == 4) and (q == 15):
                self.state = 34

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 33:
            if (x == 1) and (z == 4) and (q == 15):
                self.state = 36

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 34:
            if (x == 3) and (z == 4) and (q == 15):
                self.state = 35

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 35:
            if (x == 4) and (z == 4) and (q == 15):
                self.state = 17

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 2) and (z == 4) and (q == 15):
                self.state = 31

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 3) and (z == 4) and (q == 15):
                self.state = 34

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 36:
            if (x == 0) and (z == 4) and (q == 15):
                self.state = 37

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 2) and (z == 4) and (q == 15):
                self.state = 31

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 1) and (z == 4) and (q == 15):
                self.state = 33

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 37:
            if (x == 0) and (z == 4) and (q == 15):
                self.state = 38

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 38:
            if (x == 0) and (z == 4) and (q == 15):
                self.state = 37

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 0) and (z == 3) and (q == 12):
                self.state = 39

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 1) and (z == 4) and (q == 15):
                self.state = 33

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 39:
            if (x == 0) and (z == 3) and (q == 12):
                self.state = 40

                output["X_t"] = 2
                output["Z_t"] = 2
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 40:
            if (x == 0) and (z == 4) and (q == 12):
                self.state = 41

                output["X_t"] = 2
                output["Z_t"] = 2
                output["turn"] = 1
            elif (x == 0) and (z == 2) and (q == 12):
                self.state = 42

                output["X_t"] = 2
                output["Z_t"] = 2
                output["turn"] = 1
            elif (x == 0) and (z == 3) and (q == 12):
                self.state = 43

                output["X_t"] = 2
                output["Z_t"] = 2
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 41:
            if (x == 0) and (z == 4) and (q == 12):
                self.state = 138

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 42:
            if (x == 0) and (z == 2) and (q == 12):
                self.state = 48

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 43:
            if (x == 0) and (z == 3) and (q == 12):
                self.state = 44

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 44:
            if (x == 0) and (z == 4) and (q == 12):
                self.state = 45

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 0) and (z == 2) and (q == 12):
                self.state = 46

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 0) and (z == 3) and (q == 12):
                self.state = 47

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 45:
            if (x == 0) and (z == 4) and (q == 12):
                self.state = 138

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 46:
            if (x == 0) and (z == 2) and (q == 12):
                self.state = 48

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 47:
            if (x == 0) and (z == 3) and (q == 12):
                self.state = 44

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 48:
            if (x == 0) and (z == 2) and (q == 12):
                self.state = 46

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 0) and (z == 3) and (q == 12):
                self.state = 47

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 1) and (z == 2) and (q == 12):
                self.state = 49

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 49:
            if (x == 1) and (z == 2) and (q == 12):
                self.state = 50

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 50:
            if (x == 0) and (z == 2) and (q == 12):
                self.state = 46

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 2) and (z == 2) and (q == 12):
                self.state = 51

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 1) and (z == 2) and (q == 12):
                self.state = 49

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 51:
            if (x == 2) and (z == 2) and (q == 12):
                self.state = 52

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 52:
            if (x == 2) and (z == 2) and (q == 12):
                self.state = 51

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 2) and (z == 3) and (q == 12):
                self.state = 53

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 1) and (z == 2) and (q == 12):
                self.state = 49

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 3) and (z == 2) and (q == 12):
                self.state = 54

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 53:
            if (x == 2) and (z == 3) and (q == 12):
                self.state = 115

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 54:
            if (x == 3) and (z == 2) and (q == 12):
                self.state = 55

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 55:
            if (x == 4) and (z == 2) and (q == 12):
                self.state = 56

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 2) and (z == 2) and (q == 12):
                self.state = 51

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 3) and (z == 2) and (q == 12):
                self.state = 54

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 56:
            if (x == 4) and (z == 2) and (q == 12):
                self.state = 57

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 57:
            if (x == 4) and (z == 2) and (q == 12):
                self.state = 56

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 4) and (z == 1) and (q == 9):
                self.state = 58

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 3) and (z == 2) and (q == 12):
                self.state = 54

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 58:
            if (x == 4) and (z == 1) and (q == 9):
                self.state = 59

                output["X_t"] = 2
                output["Z_t"] = 0
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 59:
            if (x == 4) and (z == 0) and (q == 9):
                self.state = 60

                output["X_t"] = 2
                output["Z_t"] = 0
                output["turn"] = 1
            elif (x == 4) and (z == 2) and (q == 9):
                self.state = 61

                output["X_t"] = 2
                output["Z_t"] = 0
                output["turn"] = 1
            elif (x == 4) and (z == 1) and (q == 9):
                self.state = 62

                output["X_t"] = 2
                output["Z_t"] = 0
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 60:
            if (x == 4) and (z == 0) and (q == 9):
                self.state = 114

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 61:
            if (x == 4) and (z == 2) and (q == 9):
                self.state = 67

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 62:
            if (x == 4) and (z == 1) and (q == 9):
                self.state = 63

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 63:
            if (x == 4) and (z == 0) and (q == 9):
                self.state = 64

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 4) and (z == 2) and (q == 9):
                self.state = 65

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 4) and (z == 1) and (q == 9):
                self.state = 66

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 64:
            if (x == 4) and (z == 0) and (q == 9):
                self.state = 114

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 65:
            if (x == 4) and (z == 2) and (q == 9):
                self.state = 67

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 66:
            if (x == 4) and (z == 1) and (q == 9):
                self.state = 63

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 67:
            if (x == 4) and (z == 2) and (q == 9):
                self.state = 65

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 4) and (z == 1) and (q == 9):
                self.state = 66

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 3) and (z == 2) and (q == 9):
                self.state = 68

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 68:
            if (x == 3) and (z == 2) and (q == 9):
                self.state = 69

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 69:
            if (x == 4) and (z == 2) and (q == 9):
                self.state = 65

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 2) and (q == 9):
                self.state = 70

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 3) and (z == 2) and (q == 9):
                self.state = 68

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 70:
            if (x == 2) and (z == 2) and (q == 9):
                self.state = 71

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 71:
            if (x == 2) and (z == 2) and (q == 9):
                self.state = 70

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 1) and (q == 9):
                self.state = 72

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 3) and (q == 9):
                self.state = 73

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 1) and (z == 2) and (q == 9):
                self.state = 74

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 3) and (z == 2) and (q == 9):
                self.state = 68

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 72:
            if (x == 2) and (z == 1) and (q == 9):
                self.state = 105

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 73:
            if (x == 2) and (z == 3) and (q == 9):
                self.state = 104

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 74:
            if (x == 1) and (z == 2) and (q == 9):
                self.state = 75

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 75:
            if (x == 0) and (z == 2) and (q == 9):
                self.state = 76

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 2) and (q == 9):
                self.state = 70

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 1) and (z == 2) and (q == 9):
                self.state = 74

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 76:
            if (x == 0) and (z == 2) and (q == 9):
                self.state = 77

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 77:
            if (x == 0) and (z == 2) and (q == 9):
                self.state = 76

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 0) and (z == 3) and (q == 9):
                self.state = 78

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 1) and (z == 2) and (q == 9):
                self.state = 74

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 78:
            if (x == 0) and (z == 3) and (q == 9):
                self.state = 79

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 79:
            if (x == 0) and (z == 4) and (q == 9):
                self.state = 80

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 0) and (z == 2) and (q == 9):
                self.state = 76

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 0) and (z == 3) and (q == 9):
                self.state = 78

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 80:
            if (x == 0) and (z == 4) and (q == 9):
                self.state = 81

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 81:
            if (x == 0) and (z == 4) and (q == 9):
                self.state = 80

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 0) and (z == 3) and (q == 9):
                self.state = 78

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 1) and (z == 4) and (q == 9):
                self.state = 82

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 82:
            if (x == 1) and (z == 4) and (q == 9):
                self.state = 83

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 83:
            if (x == 0) and (z == 4) and (q == 9):
                self.state = 80

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 4) and (q == 9):
                self.state = 84

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 1) and (z == 4) and (q == 9):
                self.state = 82

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 84:
            if (x == 2) and (z == 4) and (q == 9):
                self.state = 85

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 85:
            if (x == 2) and (z == 4) and (q == 9):
                self.state = 84

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 5) and (q == 9):
                self.state = 86

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 3) and (q == 9):
                self.state = 73

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 1) and (z == 4) and (q == 9):
                self.state = 82

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 3) and (z == 4) and (q == 9):
                self.state = 87

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 86:
            if (x == 2) and (z == 5) and (q == 9):
                self.state = 103

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 87:
            if (x == 3) and (z == 4) and (q == 9):
                self.state = 88

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 88:
            if (x == 4) and (z == 4) and (q == 9):
                self.state = 89

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 4) and (q == 9):
                self.state = 84

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 3) and (z == 4) and (q == 9):
                self.state = 87

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 89:
            if (x == 4) and (z == 4) and (q == 9):
                self.state = 90

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 90:
            if (x == 4) and (z == 4) and (q == 9):
                self.state = 89

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 4) and (z == 5) and (q == 9):
                self.state = 91

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 3) and (z == 4) and (q == 9):
                self.state = 87

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 91:
            if (x == 4) and (z == 5) and (q == 9):
                self.state = 92

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 92:
            if (x == 4) and (z == 4) and (q == 9):
                self.state = 89

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 4) and (z == 6) and (q == 9):
                self.state = 93

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 4) and (z == 5) and (q == 9):
                self.state = 91

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 93:
            if (x == 4) and (z == 6) and (q == 9):
                self.state = 94

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 94:
            if (x == 4) and (z == 6) and (q == 9):
                self.state = 93

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 4) and (z == 5) and (q == 9):
                self.state = 91

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 3) and (z == 6) and (q == 9):
                self.state = 95

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 95:
            if (x == 3) and (z == 6) and (q == 9):
                self.state = 96

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 96:
            if (x == 4) and (z == 6) and (q == 9):
                self.state = 93

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 6) and (q == 9):
                self.state = 97

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 3) and (z == 6) and (q == 9):
                self.state = 95

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 97:
            if (x == 2) and (z == 6) and (q == 9):
                self.state = 98

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 98:
            if (x == 2) and (z == 6) and (q == 9):
                self.state = 97

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 5) and (q == 9):
                self.state = 86

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 1) and (z == 6) and (q == 9):
                self.state = 99

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 3) and (z == 6) and (q == 9):
                self.state = 95

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 99:
            if (x == 1) and (z == 6) and (q == 9):
                self.state = 100

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 100:
            if (x == 0) and (z == 6) and (q == 9):
                self.state = 101

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 6) and (q == 9):
                self.state = 97

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 1) and (z == 6) and (q == 9):
                self.state = 99

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 101:
            if (x == 0) and (z == 6) and (q == 9):
                self.state = 102

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 102:
            if (x == 0) and (z == 6) and (q == 9):
                self.state = 101

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 1) and (z == 6) and (q == 9):
                self.state = 99

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 103:
            if (x == 2) and (z == 4) and (q == 9):
                self.state = 84

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 6) and (q == 9):
                self.state = 97

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 5) and (q == 9):
                self.state = 86

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 104:
            if (x == 2) and (z == 4) and (q == 9):
                self.state = 84

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 2) and (q == 9):
                self.state = 70

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 3) and (q == 9):
                self.state = 73

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 105:
            if (x == 2) and (z == 0) and (q == 9):
                self.state = 106

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 2) and (q == 9):
                self.state = 70

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 1) and (q == 9):
                self.state = 72

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 106:
            if (x == 2) and (z == 0) and (q == 9):
                self.state = 107

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 107:
            if (x == 2) and (z == 0) and (q == 9):
                self.state = 106

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 1) and (q == 9):
                self.state = 72

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 1) and (z == 0) and (q == 9):
                self.state = 108

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 3) and (z == 0) and (q == 9):
                self.state = 109

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 108:
            if (x == 1) and (z == 0) and (q == 9):
                self.state = 111

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 109:
            if (x == 3) and (z == 0) and (q == 9):
                self.state = 110

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 110:
            if (x == 4) and (z == 0) and (q == 9):
                self.state = 64

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 0) and (q == 9):
                self.state = 106

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 3) and (z == 0) and (q == 9):
                self.state = 109

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 111:
            if (x == 0) and (z == 0) and (q == 1):
                self.state = 112

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 2) and (z == 0) and (q == 9):
                self.state = 106

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 1) and (z == 0) and (q == 9):
                self.state = 108

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 112:
            if (x == 0) and (z == 0) and (q == 1):
                self.state = 113

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 113:
            if (x == 0) and (z == 0) and (q == 1):
                self.state = 112

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 114:
            if (x == 4) and (z == 0) and (q == 9):
                self.state = 64

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 4) and (z == 1) and (q == 9):
                self.state = 66

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            elif (x == 3) and (z == 0) and (q == 9):
                self.state = 109

                output["X_t"] = 2
                output["Z_t"] = -1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 115:
            if (x == 2) and (z == 4) and (q == 12):
                self.state = 116

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 2) and (z == 2) and (q == 12):
                self.state = 51

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 2) and (z == 3) and (q == 12):
                self.state = 53

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 116:
            if (x == 2) and (z == 4) and (q == 12):
                self.state = 117

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 117:
            if (x == 2) and (z == 4) and (q == 12):
                self.state = 116

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 2) and (z == 5) and (q == 12):
                self.state = 118

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 2) and (z == 3) and (q == 12):
                self.state = 53

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 1) and (z == 4) and (q == 12):
                self.state = 119

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 3) and (z == 4) and (q == 12):
                self.state = 120

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 118:
            if (x == 2) and (z == 5) and (q == 12):
                self.state = 137

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 119:
            if (x == 1) and (z == 4) and (q == 12):
                self.state = 136

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 120:
            if (x == 3) and (z == 4) and (q == 12):
                self.state = 121

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 121:
            if (x == 4) and (z == 4) and (q == 12):
                self.state = 122

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 2) and (z == 4) and (q == 12):
                self.state = 116

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 3) and (z == 4) and (q == 12):
                self.state = 120

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 122:
            if (x == 4) and (z == 4) and (q == 12):
                self.state = 123

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 123:
            if (x == 4) and (z == 4) and (q == 12):
                self.state = 122

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 4) and (z == 5) and (q == 12):
                self.state = 124

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 3) and (z == 4) and (q == 12):
                self.state = 120

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 124:
            if (x == 4) and (z == 5) and (q == 12):
                self.state = 125

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 125:
            if (x == 4) and (z == 4) and (q == 12):
                self.state = 122

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 4) and (z == 6) and (q == 12):
                self.state = 126

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 4) and (z == 5) and (q == 12):
                self.state = 124

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 126:
            if (x == 4) and (z == 6) and (q == 12):
                self.state = 127

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 127:
            if (x == 4) and (z == 6) and (q == 12):
                self.state = 126

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 4) and (z == 5) and (q == 12):
                self.state = 124

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 3) and (z == 6) and (q == 12):
                self.state = 128

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 128:
            if (x == 3) and (z == 6) and (q == 12):
                self.state = 129

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 129:
            if (x == 4) and (z == 6) and (q == 12):
                self.state = 126

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 2) and (z == 6) and (q == 12):
                self.state = 130

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 3) and (z == 6) and (q == 12):
                self.state = 128

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 130:
            if (x == 2) and (z == 6) and (q == 12):
                self.state = 131

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 131:
            if (x == 2) and (z == 6) and (q == 12):
                self.state = 130

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 2) and (z == 5) and (q == 12):
                self.state = 118

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 1) and (z == 6) and (q == 12):
                self.state = 132

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 3) and (z == 6) and (q == 12):
                self.state = 128

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 132:
            if (x == 1) and (z == 6) and (q == 12):
                self.state = 133

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 133:
            if (x == 0) and (z == 6) and (q == 12):
                self.state = 134

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 2) and (z == 6) and (q == 12):
                self.state = 130

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 1) and (z == 6) and (q == 12):
                self.state = 132

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 134:
            if (x == 0) and (z == 6) and (q == 12):
                self.state = 135

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 0
            else:
                self._error(x, z, q)
        elif self.state == 135:
            if (x == 0) and (z == 6) and (q == 12):
                self.state = 134

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 1) and (z == 6) and (q == 12):
                self.state = 132

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 136:
            if (x == 0) and (z == 4) and (q == 12):
                self.state = 45

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 2) and (z == 4) and (q == 12):
                self.state = 116

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 1) and (z == 4) and (q == 12):
                self.state = 119

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 137:
            if (x == 2) and (z == 4) and (q == 12):
                self.state = 116

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 2) and (z == 6) and (q == 12):
                self.state = 130

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 2) and (z == 5) and (q == 12):
                self.state = 118

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 138:
            if (x == 0) and (z == 4) and (q == 12):
                self.state = 45

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 0) and (z == 3) and (q == 12):
                self.state = 47

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            elif (x == 1) and (z == 4) and (q == 12):
                self.state = 119

                output["X_t"] = 2
                output["Z_t"] = 1
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 139:
            if (x == 4) and (z == 4) and (q == 15):
                self.state = 17

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 4) and (z == 5) and (q == 15):
                self.state = 19

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            elif (x == 3) and (z == 4) and (q == 15):
                self.state = 34

                output["X_t"] = 2
                output["Z_t"] = 3
                output["turn"] = 1
            else:
                self._error(x, z, q)
        elif self.state == 140:
            if (x == 0) and (z == 6) and (q == 0):
                self.state = 0

                output["X_t"] = 2
                output["Z_t"] = 6
                output["turn"] = 1
            else:
                self._error(x, z, q)
        else:
            raise Exception("Unrecognized internal state: " + str(self.state))
        return output

    def _error(self, x, z, q):
        raise ValueError("Unrecognized input: " + (
            "x = {x}; "
            "z = {z}; "
            "q = {q}; ").format(
                x=x,
                z=z,
                q=q))
