class TesterCtrl(object):
    """Mealy transducer.

    Internal states are integers, the current state
    is stored in the attribute "state".
    To take a transition, call method "move".

    The names of input variables are stored in the
    attribute "input_vars".

    Automatically generated by tulip.dumpsmach on 2023-09-12 19:02:05 UTC
    To learn more about TuLiP, visit http://tulip-control.org
    """
    def __init__(self):
        self.state = 22
        self.input_vars = ['z', 'x']

    def move(self, z, x):
        """Given inputs, take move and return outputs.

        @rtype: dict
        @return: dictionary with keys of the output variable names:
            ['env_z', 'env_x']
        """
        output = dict()
        if self.state == 0:
            if (z == 4) and (x == 0):
                self.state = 0

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 4) and (x == 1):
                self.state = 1

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 1:
            if (z == 4) and (x == 0):
                self.state = 0

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 4) and (x == 2):
                self.state = 2

                output["env_z"] = 3
                output["env_x"] = 2
            elif (z == 4) and (x == 1):
                self.state = 1

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 2:
            if (z == 4) and (x == 2):
                self.state = 2

                output["env_z"] = 3
                output["env_x"] = 2
            elif (z == 4) and (x == 1):
                self.state = 1

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 4) and (x == 3):
                self.state = 3

                output["env_z"] = 4
                output["env_x"] = 2
            elif (z == 3) and (x == 2):
                self.state = 4

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 3:
            if (z == 4) and (x == 4):
                self.state = 20

                output["env_z"] = 4
                output["env_x"] = 2
            elif (z == 4) and (x == 2):
                self.state = 2

                output["env_z"] = 3
                output["env_x"] = 2
            elif (z == 4) and (x == 3):
                self.state = 3

                output["env_z"] = 4
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 4:
            if (z == 4) and (x == 2):
                self.state = 2

                output["env_z"] = 3
                output["env_x"] = 2
            elif (z == 2) and (x == 2):
                self.state = 5

                output["env_z"] = 1
                output["env_x"] = 2
            elif (z == 3) and (x == 2):
                self.state = 4

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 5:
            if (z == 2) and (x == 2):
                self.state = 5

                output["env_z"] = 1
                output["env_x"] = 2
            elif (z == 2) and (x == 1):
                self.state = 6

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 2) and (x == 3):
                self.state = 7

                output["env_z"] = 1
                output["env_x"] = 2
            elif (z == 1) and (x == 2):
                self.state = 8

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 3) and (x == 2):
                self.state = 4

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 6:
            if (z == 2) and (x == 0):
                self.state = 15

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 2) and (x == 2):
                self.state = 5

                output["env_z"] = 1
                output["env_x"] = 2
            elif (z == 2) and (x == 1):
                self.state = 6

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 7:
            if (z == 2) and (x == 4):
                self.state = 16

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 2) and (x == 2):
                self.state = 5

                output["env_z"] = 1
                output["env_x"] = 2
            elif (z == 2) and (x == 3):
                self.state = 7

                output["env_z"] = 1
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 8:
            if (z == 0) and (x == 2):
                self.state = 9

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 2) and (x == 2):
                self.state = 5

                output["env_z"] = 1
                output["env_x"] = 2
            elif (z == 1) and (x == 2):
                self.state = 8

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 9:
            if (z == 0) and (x == 2):
                self.state = 9

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 0) and (x == 1):
                self.state = 10

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 0) and (x == 3):
                self.state = 11

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 1) and (x == 2):
                self.state = 8

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 10:
            if (z == 0) and (x == 0):
                self.state = 13

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 0) and (x == 2):
                self.state = 9

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 0) and (x == 1):
                self.state = 10

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 11:
            if (z == 0) and (x == 4):
                self.state = 12

                output["env_z"] = 1
                output["env_x"] = 2
            elif (z == 0) and (x == 2):
                self.state = 9

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 0) and (x == 3):
                self.state = 11

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 12:
            if (z == 0) and (x == 4):
                self.state = 12

                output["env_z"] = 1
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 13:
            if (z == 0) and (x == 0):
                self.state = 13

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 0) and (x == 1):
                self.state = 10

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 1) and (x == 0):
                self.state = 14

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 14:
            if (z == 0) and (x == 0):
                self.state = 13

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 2) and (x == 0):
                self.state = 15

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 1) and (x == 0):
                self.state = 14

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 15:
            if (z == 2) and (x == 0):
                self.state = 15

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 2) and (x == 1):
                self.state = 6

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 1) and (x == 0):
                self.state = 14

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 16:
            if (z == 2) and (x == 4):
                self.state = 16

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 2) and (x == 3):
                self.state = 7

                output["env_z"] = 1
                output["env_x"] = 2
            elif (z == 3) and (x == 4):
                self.state = 17

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 17:
            if (z == 4) and (x == 4):
                self.state = 18

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 2) and (x == 4):
                self.state = 16

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 3) and (x == 4):
                self.state = 17

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 18:
            if (z == 4) and (x == 4):
                self.state = 18

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 4) and (x == 3):
                self.state = 19

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 3) and (x == 4):
                self.state = 17

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 19:
            if (z == 4) and (x == 4):
                self.state = 18

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 4) and (x == 2):
                self.state = 2

                output["env_z"] = 3
                output["env_x"] = 2
            elif (z == 4) and (x == 3):
                self.state = 19

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 20:
            if (z == 4) and (x == 4):
                self.state = 20

                output["env_z"] = 4
                output["env_x"] = 2
            elif (z == 4) and (x == 3):
                self.state = 3

                output["env_z"] = 4
                output["env_x"] = 2
            elif (z == 3) and (x == 4):
                self.state = 21

                output["env_z"] = 3
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 21:
            if (z == 4) and (x == 4):
                self.state = 20

                output["env_z"] = 4
                output["env_x"] = 2
            elif (z == 2) and (x == 4):
                self.state = 16

                output["env_z"] = 2
                output["env_x"] = 2
            elif (z == 3) and (x == 4):
                self.state = 17

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        elif self.state == 22:
            if (z == 4) and (x == 0):
                self.state = 0

                output["env_z"] = 2
                output["env_x"] = 2
            else:
                self._error(z, x)
        else:
            raise Exception("Unrecognized internal state: " + str(self.state))
        return output

    def _error(self, z, x):
        raise ValueError("Unrecognized input: " + (
            "z = {z}; "
            "x = {x}; ").format(
                z=z,
                x=x))
